apiVersion: v1
kind: Service
metadata:
  name: comment-api
spec:
  type: ClusterIP
  ports: 
  - name: grpc
    port: 8081
    targetPort: 8081
  - name: prometheus
    port: 2222
    targetPort: 2222
        
